api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json:   ['application/json']
        xml:    ['application/xml', 'text1/xml']
        jsonld: ['application/ld+json']
        csv:    ['text/csv']
